### ISSUE TITLE
When hovering over buttons underline is visible

### ISSUE THREAD

**Issue by lennyg1** [AppaYY/fitnesse-bootstrap-plus-theme#31]
![image](https://user-images.githubusercontent.com/30591999/76416226-f5501100-639a-11ea-984e-60e498453dcf.png)

The little line in the screenshot is caused by an underline on one of the elements within the button that's still visible.

**Comment by Lizzze** [comment]
We have added the issues to the backlog of our Trello board

https://trello.com/c/4pfpcbv9/205-bug-6-header-knoppen-krijgt-een-underline

**Comment by lennyg1** [comment]
Buttons seem to have been removed.
