### ISSUE TITLE
Hardcoded extra header is a surprise

### ISSUE THREAD

**Issue by lennyg1** [AppaYY/fitnesse-bootstrap-plus-theme#32]
Currently I rebuild my header based on my target audience and environment. This includes adding or removing buttons and other elements I might want to use. Sometimes just a line, sometimes a separate menu with specific functionality. Somethings something entirely different that integrates with my SUT.

To create this, I use documentation within the FitNesse UserGuide, like;
http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.WritingAcceptanceTests.SpecialPages
http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.FitNesseWiki.MarkupLanguageReference.MarkupStyle

This means that a 2nd major header that's now by default in bootstrap-plus might have unintended side-effects when I also have a larger pageheader for whatever reason. Considering this is base functionality of FitNesse, it's not unlikely that some other user might be using the header in unexpected ways as well.

I'm actually using similar buttons for an example;

![image](https://user-images.githubusercontent.com/30591999/76416625-b3739a80-639b-11ea-990a-563e35248045.png)

**Comment by Lizzze** [comment]
We have added the issues to the backlog of our Trello board

https://trello.com/c/Wc4PwiP7/208-us-60-hard-gecodeerde-header-weghalen

**Comment by maartenjanvangool** [comment]
I think you were not the only one complaining, I think this is changed in https://github.com/praegus/toolchain-fitnesse-plugin/releases/tag/toolchain-fitnesse-plugin-2.0.1

**Comment by Lizzze** [comment]
This issue is fixed.
