### ISSUE TITLE
Font sharpening is overdoing it

### ISSUE THREAD

**Issue by lennyg1** [AppaYY/fitnesse-bootstrap-plus-theme#35]
Original:
![image](https://user-images.githubusercontent.com/30591999/76417887-fa628f80-639d-11ea-8356-315cdf807dcd.png)
![image](https://user-images.githubusercontent.com/30591999/76418169-6fce6000-639e-11ea-8bb8-8e88f8a92014.png)

Current:
![image](https://user-images.githubusercontent.com/30591999/76417906-08181500-639e-11ea-9767-defa736b5421.png)
![image](https://user-images.githubusercontent.com/30591999/76418196-82489980-639e-11ea-93ec-b7cd51f29f5a.png)

I find the font sharpening somewhat strong here. I preferred the softer touch of the original design. Especially on not that great displays and projectors, the sharper fonts become difficult to read.

I understand the color changes, definitely a nice touch... Just maybe a little softer? Note that the dark side of the thing actually does have more comfortable fonts.

**Comment by Lizzze** [comment]
We have added the issues to the backlog of our Trello board

https://trello.com/c/f1uK54tP/206-contents-kleuren-in-de-light-theme-verzachten

**Comment by Lizzze** [comment]
This issue has been fixed in this [pull request](https://github.com/praegus/fitnesse-bootstrap-plus-theme/pull/56).
