### ISSUE TITLE
Viewing files section with sidebar on causes 400 and 404 errors

### ISSUE THREAD

**Issue by lennyg1** [AppaYY/fitnesse-bootstrap-plus-theme#36]
Enable sidebar, open files from menu (Tools>Files).

The responder for the toc has issues loading a toc. Which actually makes sense for the files section.

**Comment by Lizzze** [comment]
We have added the issues to the backlog of our Trello board

**Comment by Lizzze** [comment]
We fixed the bug by hiding the sidebar. We made a new [feature request card](https://trello.com/c/wsqGbRDy/) in our backlog related to this issue.
