### ISSUE TITLE
Move + sign, to add new tag, behind existing tags

### ISSUE THREAD

**Issue by lennyg1** [AppaYY/fitnesse-bootstrap-plus-theme#37]
Adding tags now always happens directly after the TOC element, it might look more natural to have the + to add more tags, after the current tags, to avoid the uncanny empty space between the tags and the title when the + icon to add a new tag isn't visible.

**Comment by PandoraMedusa** [comment]
We have actively chosen to put the plus symbol before the existing tags, this is why we are closing this issue. Thank you for your feedback.

-- Development team
