### ISSUE TITLE
Expand All doesn't work anymore on pages

### ISSUE THREAD

**Issue by lennyg1** [AppaYY/fitnesse-bootstrap-plus-theme#38]
Expand all button doesn't work anymore on ScenarioLibraries and other pages. Using the button causes the following error:

Uncaught TypeError: section.find(...).andSelf is not a function
    at HTMLAnchorElement.<anonymous> (fitnesse.js:40)
    at HTMLDocument.dispatch (jquery-3.4.1.min.js:2)
    at HTMLDocument.v.handle (jquery-3.4.1.min.js:2)

**Comment by Lizzze** [comment]
We have added the issues to the backlog of our Trello board

https://trello.com/c/eRlw6sK3/204-bug-5-expand-all-knop-werkt-niet-meer-op-de-pagina

**Comment by maartenjanvangool** [comment]
I think this one is fixed in 2.0.1 https://github.com/praegus/toolchain-fitnesse-plugin/releases/tag/toolchain-fitnesse-plugin-2.0.1
