### ISSUE TITLE
Add empty css stylesheet to skeleton.vm to easily override theming

### ISSUE THREAD

**Issue by lennyg1** [AppaYY/fitnesse-bootstrap-plus-theme#39]
For sales purposes and usability reasons, I sometimes change minor details about the color scheme of FitNesse. Occasionally I want special buttons and I like to make a proper design for those. Sometimes I want to include a company logo in the design of FitNesse, by replacing the samewhat low-resolution and outdated FitNesse logo.

To add this functionality, I create an override css file that I add to skeleton.vm myself.

Would it be possible to add an empty css file to bootstrap-plus that I can overwrite/fill myself? An example of what I use in skeleton.vm:

```
    <link rel="stylesheet" type="text/css" href="${contextRoot}files/fitnesse/bootstrap-plus/css/jquery-ui-1.12.1.min.css">
    <link rel="stylesheet" type="text/css" href="${contextRoot}files/fitnesse/css/custom.css" />

    <script src="${contextRoot}files/fitnesse/js/jquery-3.4.1.min.js" type="text/javascript"></script>

```

**Comment by PandoraMedusa** [comment]
We have added the issues to the backlog of our Trello board

https://trello.com/c/fBjqJqWs/209-us-61-leeg-stylesheet-toevoegen-aan-skeletonvm

**Comment by Alexpen97** [comment]
in overleg is de userstory geupdate om ook een lege javascript file toe te voegen.
https://trello.com/c/fBjqJqWs/209-us-61-lege-stylesheet-en-javascript-file-toevoegen-aan-skeletonvm

**Comment by Alexpen97** [comment]
This issue has been resolved, an empty stylesheet and javascript file have been added to the bootstrap.
