### ISSUE TITLE
Typo in Bootstrap Preferences menu

### ISSUE THREAD

**Issue by joroelev** [AppaYY/fitnesse-bootstrap-plus-theme#44]
![afbeelding](https://user-images.githubusercontent.com/5476742/77315037-1ef82900-6d07-11ea-8ce0-937f1626946c.png)

Found in 2.0.5: _Highlight Slim Symbols & Expressionsh_ should be _Highlight Slim Symbols & Expressions_

**Comment by Lizzze** [comment]
We have added the issues to the backlog of our Trello board

https://trello.com/c/gLKYObbd/

**Comment by Lizzze** [comment]
We fixed the bug
